# Generated by Django 3.0.6 on 2020-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200629_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time_created',
            field=models.DateTimeField(default='2020-06-29 12:36:41'),
        ),
    ]
