# Generated by Django 3.0.6 on 2020-06-29 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200629_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time_created',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
